name: NoxisAPI
version: 1.2
main: fr.kitsxki_.noxisapi.NoxisAPI
authors: [ Kitsxki_ ]
description: API of NoxisMC's plugins.
commands:
  coins:
    aliases:
      - c
  ping:
    aliases:
      - getping